Part5.1
tomer99a/encryptionDecryption pull request #8
Opened 2023-03-02 09:37 UTC by tomer99a

2023-03-09 08:17 UTC, Gil8513 requested changes
Looks good!

1) what about logging errors and other information?
2) what about the EncryptionLogEventArgs from the exercise?
3) what about the question about the concurrent access to the logger?

2023-03-09 08:17 UTC, Gil8513 commented on src/main/log/HandlerEvent.java
> +public class HandlerEvent {
Change to ```EventHandler```, this sounds better in English. 
Also, consider moving it outside the ```log``` dir, because it might not be used solely for logs.

2023-03-09 08:17 UTC, Gil8513 commented on src/main/log/EventEncrypt.java
> +    public EventEncrypt(Class<?> clazz) {
Also here, you need to change the word order to ```EncryptEvent```.
However, the class name is misleading. it does not represent an event but rather an event handler.
A better name might be ```EncryptionEventLogHandler``` or ```EncryptionEventLogger```

2023-03-09 08:17 UTC, Gil8513 commented on src/main/log/EventDecrypt.java
> +public class EventDecrypt extends EventAbstract {
same here

2023-03-09 08:17 UTC, Gil8513 commented on src/main/log/Register.java
> +    protected void logRegister(EventAbstract eventAbstract) {
why is it called ```logRegister```? also why is protected?

2023-03-09 08:17 UTC, Gil8513 commented on src/main/log/EventAbstract.java
> +    public EventAbstract(final Class<?> clazz) {
As I said before, this is not an event but rather an event handler, or observer, or subscriber.

2023-03-09 08:17 UTC, Gil8513 commented on src/main/log/EventAbstract.java
> +    abstract void writeMessage(boolean startStatus, boolean single);
It's not a good name because it indicates that all event handlers are writing messages. However, maybe for future use, there might be different things to do upon events.

2023-03-09 08:17 UTC, Gil8513 commented on src/main/dirEncryption/DirectoryProcessorAbstract.java
> +    protected void handelEncrypt(String fileName, File file, IEncryptionAlgorithm<T> algo, T key) {
typo: handel -> handle

2023-03-09 08:17 UTC, Gil8513 commented on src/main/dirEncryption/DirectoryProcessorAbstract.java
> +    protected void handelDecrypt(String fileName, File file, IEncryptionAlgorithm<T> algo, T key) {
typo: handel -> handle

2023-03-09 08:17 UTC, Gil8513 commented on src/main/dirEncryption/AsyncDirectoryProcessor.java
> +
There are some code duplications between the functions.

2023-03-09 08:17 UTC, Gil8513 commented on src/main/dirEncryption/AsyncDirectoryProcessor.java
> +
Consider using a thread pool executor, instead of creating a new thread each time. 
If you have a directory of 200 files, you wouldn't want to open 200 threads.

2023-03-12 14:39 UTC, Gil8513 requested changes

2023-03-12 14:39 UTC, Gil8513 commented on src/main/log/SubscriberLog4jLogger.java
> +        data = new EncryptionLogEventArgs(fileName, clazz.getName());
The ```EncryptionLogEventArgs``` should be created when the event occurs, not in the constructor! It is unique to each event.

2023-03-12 14:39 UTC, Gil8513 commented on src/main/FileEncryptor.java
> +        EventHandler eventHandler = new EventHandler(encryptionAlgo.getClass(), file.getName());
Why are you creating a new event handler each encryption? Can you not use the same one? 
Why is there a unique EventHandler for every file? Why is it not passed as argument?

2023-03-12 14:39 UTC, Gil8513 commented on src/main/dirEncryption/AsyncDirectoryProcessor.java
> +    static final int MAX_T = 5;
Why 5? Can you think of a better and more explainable number?

2023-03-12 14:39 UTC, Gil8513 commented on src/main/dirEncryption/AsyncDirectoryProcessor.java
> +    private void help(IEncryptionAlgorithm<T> algo, T key, File inputFolder, File outputFolder, boolean isEncrypt) throws IOException {
WTF is help?? what is this function??

2023-03-12 14:39 UTC, Gil8513 commented on src/main/dirEncryption/AsyncDirectoryProcessor.java
> +                if (fileName.contains("key")) {
Why not put the key in a different directory?

2023-03-12 14:39 UTC, Gil8513 commented on src/main/dirEncryption/AsyncDirectoryProcessor.java
> +                Runnable myThread = () -> {
use a better name than ```myThread```.
You don't even have to insert it to variable, you can just insert it to the pool directly.

2023-03-12 14:39 UTC, Gil8513 commented on src/main/dirEncryption/AsyncDirectoryProcessor.java
> +                Future<?> future = pool.submit(myThread);
Why are you saving all the futures? Are you using them other than to wait for completion?
If so, you can use the ```awaitTermination``` function

2023-03-12 14:39 UTC, Gil8513 commented on src/main/log/ErrorLog4jLogger.java
> +        Logger logger = LogManager.getLogger(clazz);
The logger should be created statically or in the constructor. Also, this class seems redundant because it only calls ```logger.error``` so why not call it directly?

2023-03-12 14:39 UTC, Gil8513 commented on src/main/encryption/EncryptionAlgorithmAbstract.java
> +    protected abstract void actualEncrypt(final String originalPath, final String outputPath, final T keyPath) throws IOException;
Think of a better name than ```actual```.
Also, explain yourself using javadocs and comments in the code.

2023-03-12 14:39 UTC, Gil8513 commented on src/test/main/dirEncryption/DirectoryProcessorAbstractTest.java
> +        //TODO: add after all that delete all the tmp files.
what is this todo?

2023-03-12 14:39 UTC, Gil8513 commented on src/main/dirEncryption/DirectoryProcessorAbstract.java
> +        System.out.printf("The %s action took %.3f minutes (%.0f seconds)%n", action, minutes, sec);
Print to log and not system out!

2023-03-12 14:39 UTC, Gil8513 commented on src/main/encryption/charAlgo/CharEncryptionAlgorithmAbstract.java
> +        System.out.printf("Location of the files are -\nencrypted - %s\nkey - %s%s", outputPath, keyPathStr, System.lineSeparator());
print to log and not stdout!

2023-03-12 14:39 UTC, Gil8513 commented on src/main/encryption/charAlgo/CharEncryptionAlgorithmAbstract.java
>          System.out.println("Location of the decrypted file is - " + outputPath);
print to log and not stdout

2023-03-12 20:29 UTC, tomer99a commented on src/main/dirEncryption/AsyncDirectoryProcessor.java
> +                if (fileName.contains("key")) {
This is what say on the task

2023-03-15 07:44 UTC, merged